Working TTrivialDS
bluehood/root pull request #1
Opened 2017-09-15 14:53 UTC by dpiparo

This PR provides the first working implementation of the TTrivialDS therewith demonstrating that the TDataSource approach works.

2017-09-15 16:54 UTC, eguiraud requested changes
A few comments inline.

I tested your PR against the latest changes in my branch: the exception you saw due to a type mismatch is gone, but it's replaced by a segfault :sweat: (which your revert still fixes). I will fix this issue asap, possibly even before merging this PR so we don't need to introduce reverts and reverts of reverts in the history.

2017-09-15 16:54 UTC, eguiraud commented on tree/treeplayer/src/TDataFrame.cxx
>  }
I would change these two lines with `fDataSource->SetNSlots(fNSlots)` in `TDFNodes.cxx:129` (`TLoopManager`'s ctor) to keep `TLoopManager` the sole authority when it comes to TDF's number of slots.

2017-09-15 16:54 UTC, eguiraud commented on tree/treeplayer/inc/ROOT/TTrivialDS.hxx
> +         return;
If this really happens it means there's a bug in TDF's logic. It would be better to throw an exception so we know if that's the case.

2017-09-15 16:54 UTC, eguiraud commented on tree/treeplayer/inc/ROOT/TTrivialDS.hxx
> +      auto chunckSize = fSize / fNSlots;
typo `chunck`

2017-09-15 16:54 UTC, eguiraud commented on tree/treeplayer/test/dataframe/datasource_trivial.cxx
> +}
If multi-threaded execution works we should add a test for it, otherwise I should fix it :smile:

2017-09-16 09:24 UTC, dpiparo commented on tree/treeplayer/test/dataframe/datasource_trivial.cxx
> +}
@bluehood , MT at the moment does not work well. Nevertheless, given that the change, whatever it is (not sure yet is in the source or in the frame), will be transparent I decided to go ahead and expose the first version of the sources we had in hands.

2017-09-16 09:24 UTC, dpiparo commented
All comments make sense. I will address them asap.

2017-09-16 18:35 UTC, dpiparo commented
All comments addressed.

2017-09-18 13:46 UTC, dpiparo commented
The PR title should be changed... I added to it too many things.

2017-09-18 13:46 UTC, closed without merging